### ISSUE TITLE
color picker doesn't hide when hsv mode is enabled on init

### ISSUE THREAD

**Issue by flurrybun** [zowepsilon/BetterColorPicker#1]
setting a pulse trigger to hsv mode and re-entering the trigger popup causes the color picker to be visible when it shouldn't be. i have to disable and re-enable hsv mode for it to disappear

![image](https://github.com/user-attachments/assets/8cfffb6d-308b-4d88-a47d-df3a6003356a)

same goes for copy color channels

![image](https://github.com/user-attachments/assets/2f7475d1-109e-4ea1-9260-83aa9c51663d)

also, i didn't want to make another issue for this but i kinda wish there was a white outline around the color picker, just to make it look more like the vanilla color picker and hide the ugly aliased edges. really solid mod tho, i find myself avoiding using the default circle color picker bc it's so imprecise so this is a big improvement ✨🐇

**Comment by zowepsilon** [comment]
fixing that in a few days

**Comment by zowepsilon** [comment]
I already tried adding a white outline but it would just make the picker a bit too small
I can probably add an option for that tho

**Comment by zowepsilon** [comment]
fixed
will try to add an option for outline later
