### ISSUE TITLE
When I exit the color menu with copy color enabled this happens!

### ISSUE THREAD

**Issue by God5Official** [zowepsilon/BetterColorPicker#2]
Only thing that make go away is unchecking & checking the copy color box again!
![Screenshot 2024-11-26 123317](https://github.com/user-attachments/assets/1624ec67-05a1-4cfe-9945-540f0e9a8b4d)

**Comment by God5Official** [comment]
v1.0.1

**Comment by zowepsilon** [comment]
already fixed. the next version is still pending on the index but it should come out in a few days

**Comment by God5Official** [comment]
Ok good to know!
