### ISSUE TITLE
Opening the color picker messes with the color

### ISSUE THREAD

**Issue by Evanineo** [zowepsilon/BetterColorPicker#3]
When you open up the color picker, sometimes it decreases one of the RGB values of the color a little bit. I think if there's a value in between the other two, that one usually gets decreased. But sometimes it just decreases one of them anyway, even if there isn't an in-between value. It's really weird.

Look at the RGB values.
https://github.com/user-attachments/assets/b0fca0f4-3407-4054-af1b-1a393d98118d

Mods that I'm using: Better Color Picker (obviously), BetterInfo, BetterInputs, Clean Startpos, Colorful Icons, Custom Keybinds, Editor Level ID API, EditorTab API, EvenMoreLevelTags, Functional, Globed, Misc Bugfixes, Node IDs, Object Workshop, SkipEditorObjects, Unlisted Objects in Editor, and some mods that don't work in 2.207.

**Comment by zowepsilon** [comment]
ok that's weird yeah
will look into it
probably related to the way i'm storing the color internally
