### ISSUE TITLE
game crashes when i close the game

### ISSUE THREAD

**Issue by MertCooler** [zowepsilon/BetterColorPicker#4]
everytime i close the game, it gives me an error and a crashlog and a tip about entering safe mode
faulty mod: BetterColorPicker
[2024-11-30_20-23-47.log](https://github.com/user-attachments/files/17966611/2024-11-30_20-23-47.log)

**Comment by zowepsilon** [comment]
betterinfo seems to be involved in the stack trace.
can you replicate the bug without betterinfo enabled?

**Comment by nichie-dv** [comment]
this more commonly happens when trying to restart the game ive found.  I dont have betterinfo in the trace, even when it's disabled, but geode seems to think this mod is outdated

**Comment by zowepsilon** [comment]
i couldn't reproduce the issue but i think i fixed it.
i'll leave this issue open for some time anyway in case the bug was not actually fixed
